# Generated by Django 2.2.2 on 2019-08-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=250)),
                ('img_desc', models.TextField()),
                ('img_url', models.CharField(max_length=250)),
            ],
        ),
    ]
